export const AnalyticsQuestions = [
  {
    id: 1,
    question: 'How do I change my password?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  },
  {
    id: 2,
    question: 'How do I change my username?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  },
  {
    id: 3,
    question: 'How do I view past sessions on the website?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  },
  {
    id: 4,
    question: 'How do I view the current open sessions?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  },
  {
    id: 5,
    question: 'How do I change my password?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  }
]

export const AppSessionQuestions = [
  {
    id: 1,
    question: 'How do I change my password?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  },
  {
    id: 2,
    question: 'How do I change my username?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  },
  {
    id: 3,
    question: 'How do I view past sessions on the website?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  },
  {
    id: 4,
    question: 'How do I view the current open sessions?',
    answer:
      'Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no.Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax. Ea sit luptatum quaerendum, his ex ignota pertinax. Tota adhuc sit in, tale equidem petentium mei no. Lorem ipsum dolor sit amet, quo minim timeam et. Ea sit luptatum quaerendum, his ex ignota pertinax.'
  }
]

export const AccountQuestions = []

export const DashboardQuestions = []
